# Site settings
title: 叽里咕噜海贼团
subtitle: by 小野不是妹纸
email: lament.wy@gmail.com
description: Don't Panic! 大胆戳右边 -->
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lament-wy.com" # the base hostname & protocol for your site
author: Lament
street_address: 阡陌路
city: 杭州
state: 浙江
#zip_code: 000000
country: 中国

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 100

# Social settings
weibo_url: http://weibo.com/CaliforniaDL
github_url: https://github.com/LamentWy
googleplus_url: https://plus.google.com/u/0/+Lament42lucky
instagram_url: n/a
# Build settings
markdown: kramdown

sass:
  style: compressed
